version: "3.3"
services:
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
  backend:
    image: node:16
    container_name: backend
    links:
      - db
    user: "root"
    restart: on-failure
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: "npm run production"
  frontend:
    image: node:16
    container_name: frontend
    links:
      - backend
    user: "root"
    restart: on-failure
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: "npm run production"
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      -   frontend
    restart: always
    ports:
      - '80:80'
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/domains:/etc/nginx/sites-enabled
